// Email utility for sending organization invitations
export const sendInvitationEmail = async (data: {
  id: string;
  role: string;
  email: string;
  organization: {
    id: string;
    name: string;
    createdAt: Date;
    slug: string;
    metadata?: any;
    logo?: string | null;
  };
  invitation: {
    id: string;
    email: string;
    inviterId: string;
    organizationId: string;
    role: string;
    status: string;
    expiresAt: Date;
    createdAt?: Date;
    teamId?: string;
  };
  inviter: {
    id: string;
    name: string;
    email: string;
  };
}, request?: Request) => {
  console.log('Sending invitation email to:', data.email);
  console.log('Organization:', data.organization.name);
  console.log('Role:', data.role);
  console.log('Invited by:', data.inviter.name);
  
  // TODO: Implement actual email sending logic
  // For now, just log the invitation details
  // You can integrate with services like:
  // - Resend
  // - SendGrid
  // - Nodemailer
  // - AWS SES
  
  // Example with console logging for development:
  console.log(`
    📧 INVITATION EMAIL
    To: ${data.email}
    Subject: You've been invited to join ${data.organization.name}
    
    Hi there!
    
    ${data.inviter.name} has invited you to join ${data.organization.name} as a ${data.role}.
    
    Click the link below to accept the invitation:
    [Invitation Link - would be generated by Better Auth]
    
    Best regards,
    The ${data.organization.name} Team
  `);
  
  return Promise.resolve();
}; 